- name: NVIDIA Container Toolkit install
  hosts: kube_control_plane[0]
  become: yes # 관리자 권한
  vars:
    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ubuntu@{{ groups["bastion"][0] }}"'

  tasks:
    - name: nvidia-ctk 설치 확인
      shell: which nvidia-container-runtime
      register: ctk_check
      ignore_errors: yes
      changed_when: false

    - name: nvidia-ctk 설치
      when: ctk_check.rc != 0
      shell: |
        curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | \
        sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
        
        curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
        sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
        sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
        
        sudo apt update

        sudo apt install -y nvidia-container-toolkit
    